Document: kubernetes
Title: Debian kubernetes Manual
Author: <insert document author here>
Abstract: This manual describes what kubernetes is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kubernetes/kubernetes.sgml.gz

Format: postscript
Files: /usr/share/doc/kubernetes/kubernetes.ps.gz

Format: text
Files: /usr/share/doc/kubernetes/kubernetes.text.gz

Format: HTML
Index: /usr/share/doc/kubernetes/html/index.html
Files: /usr/share/doc/kubernetes/html/*.html
